### ISSUE TITLE
Firefox 1.3.4, Elemental filter not working...

### ISSUE THREAD

**Issue by WarbirdXBL** [dasilva333/DIM#23]
Thanks so much!
re:Firefox 1.3.4, Elemental filter not working, 
be nice to have a reset filter button (I see it in the menu), 
can you explain the patience message? 
does there need to be an open vault slot for transfer to work / or not show the patience message?

**Comment by dasilva333** [comment]
The patience message is a known bug it'll be fixed soon. Try 1.3.8 here and report back if it's fixed: https://github.com/dasilva333/DIM/blob/div-movile-dist/destiny_item_viewer.xpi

**Comment by WarbirdXBL** [comment]
Firefox 1.3.9 (banner says 1.3.8)
A. Damage Filter now working :)
B. Clear Filters button, forget about it (menu based command system is fine for now, even though filter settings can result in zero results)
C. Patience message, have not seen it yet, will report if I do
D. The Chrome app you branched from seemed to only work if there was an available Vault slot open, which I guessed was a requirement from transfer to work, just curious...

**Comment by dasilva333** [comment]
a. good
b. clear filters work for me
c. problem fixed as of 1.3.9 officially then
d. bungie's api doesnt allow character to character transfer so i have to use the vault as a proxy

closing ticket

**Comment by WarbirdXBL** [comment]
Should I reopen, or start a new case if I have a followup such as this?

C. Nope, Patience message is still happening in 1.3.9, when transferring between characters (which is the only time I've seen it). Occurs even when there are many open Vault slots. After Patience message is dismissed, item is in Vault, and then a second transfer is required to move to destination Character. I do not mind seeing this message, and would not call it a bug (as you have, but your the boss :).  Related question, I would be very interested in hearing that despite this behavior there is absolutely no way items can get permanently lost. I would assume Bungie's API does not even allow remote dismantling?
