### ISSUE TITLE
Cannot switch between XBL & PSN

### ISSUE THREAD

**Issue by Baloras** [dasilva333/DIM#37]
I have both my XBL and PSN accounts linked to my bungie.net account. When I open the app I only see my PSN characters and cannot find anyway to switch back and forth.

**Comment by dasilva333** [comment]
i noticed you reported an issue where you can't see your PSN items only your xbox items. If you have access to the chrome extension then get it loaded and follow these instructions:

    load Ghost Tower from Chrome (https://chrome.google.com/webstore/detail/tower-ghost-for-destiny/gdjndlpockopgjbonnfdmkcmkcikjhge(

    press F12 to open the developer menu

    go to the Console tab at the end of the tabs

    type these commands:

    app.bungie.setsystem("PSN");

    app.loadData();

    Verify it loaded your PSN account, let me know the results if that works I can come up with a fix pretty easily otherwise I'm going to need your account or somebody's account so I can debug the issue.

    For extra credit try setting the PSN string back to XBL and run those commands again to see if you can toggle back and forth between the two.

Thanks for your help

**Comment by dasilva333** [comment]
I will leave this ticket open here until it is resolved hopefully @Baloras  can provide me with some feedback, otherwise I'll close the ticket and ask to reopen it in the new repo under suggestions for multi account support.

**Comment by Baloras** [comment]
I tried following the above instructions but it still just shows my PSN characters. It will not let me.switch back and forth.

**Comment by dasilva333** [comment]
Problem fixed as of 1.6.7 please try the latest version and and and close this ticket thank you

**Comment by brazenisgod** [comment]
1.6.7 has not been published as a .zip for chrome yet.  Though I have applied the changes listed throughout the git which are tagged 1.6.7 and that did not resolve the issue.  I would like to try again with a full .zip instead because...well...im not a webdev.

**Comment by dasilva333** [comment]
Try it now I just published 1.6.8 that should work for you too. thanks

**Comment by Baloras** [comment]
Awesome! I'm able to switch back and forth with the new feature. Thanks!

**Comment by brazenisgod** [comment]
Absolutely beautiful.  Well done, sir.  Can't wait to try it on mobile.

**Comment by Baloras** [comment]
In the latest update (1.7.1) the feature is gone again.

**Comment by brazenisgod** [comment]
Yes, I'll be sticking with 1.6.8 as 1.7.1 just broke everything again.

**Comment by dasilva333** [comment]
Hey guys just wnated to give you all an update on the status of the issue, I spent some time yesterday adding dual account support to the app, it was available on 1.6.7 and then I reverted the changes after that because there was an issue on the mobile platform and the changes. I'll be merging the changes back in tonight and you should expect to see it working again as of 1.7.2

Thanks

**Comment by dasilva333** [comment]
Its been fixed as of 1.7.2 try again and report back so we can finally close this ticket :)

**Comment by Baloras** [comment]
It is working again. Thanks!
